"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
const google_1 = require("next/font/google");
const Providers_1 = __importDefault(require("./components/Providers"));
require("./globals.css");
const inter = (0, google_1.Inter)({ subsets: ['latin'] });
exports.metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
};
function RootLayout({ children }) {
    return (<html lang="en">
      <body className={inter.className}>
        <Providers_1.default>{children}</Providers_1.default>
      </body>
    </html>);
}
